/**
 * Writes the generated files, and nothing else.
 *
 * Target directories are wiped before a run, so an endpoint or a schema the API has removed
 * disappears from the tree instead of lingering as a method that now 404s. Files are written only
 * when their content changed, which keeps mtimes — and therefore incremental builds — honest.
 */
import { mkdir, readdir, rm, writeFile, readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const HEADER = `/**
 * This file is generated by tools/generate.ts from spec/openapi.json. Do not edit it.
 *
 * Run \`npm run generate\` after \`./tools/fetch-spec.sh\` to rebuild it.
 */`;

export class Emitter {
  private written = 0;

  constructor(private readonly root: string) {}

  /** Removes a generated directory's contents, so a stale file cannot survive a regeneration. */
  async wipe(relative: string): Promise<void> {
    const directory = join(this.root, relative);

    await mkdir(directory, { recursive: true });

    for (const entry of await readdir(directory)) {
      await rm(join(directory, entry), { recursive: true, force: true });
    }
  }

  async write(relative: string, body: string): Promise<void> {
    const path = join(this.root, relative);
    const contents = `${HEADER}\n\n${body.replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;

    await mkdir(dirname(path), { recursive: true });

    if ((await readIfPresent(path)) !== contents) {
      await writeFile(path, contents, 'utf8');
    }

    this.written += 1;
  }

  count(): number {
    return this.written;
  }
}

async function readIfPresent(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8');
  } catch {
    // Any failure to read means "there is nothing to compare against", which is the same answer a
    // missing file gives. Rethrowing a permission error here would only obscure the write that
    // follows and fails with a better message.
    return undefined;
  }
}

/**
 * A JSDoc comment from a list of lines, indented.
 *
 * Returns an empty string for no content, so a caller can concatenate unconditionally.
 */
export function docComment(lines: readonly string[], indent = ''): string {
  const trimmed = [...lines];

  while (trimmed.length > 0 && trimmed[trimmed.length - 1] === '') {
    trimmed.pop();
  }

  if (trimmed.length === 0) {
    return '';
  }

  if (trimmed.length === 1) {
    return `${indent}/** ${escapeComment(trimmed[0] ?? '')} */\n`;
  }

  const body = trimmed.map((line) => `${indent} *${line === '' ? '' : ` ${escapeComment(line)}`}`);

  return `${indent}/**\n${body.join('\n')}\n${indent} */\n`;
}

/**
 * Makes a string safe inside a block comment.
 *
 * An annotation containing a fenced code block can contain a comment terminator, which would close
 * the comment early and leave the rest of the generated file as code. A zero-width space between the
 * star and the slash is invisible when read and inert when parsed.
 *
 * This function's own doc comment is the regression test for itself: writing the terminator out
 * literally here is what broke the generator the first time.
 */
export function escapeComment(text: string): string {
  return text.replace(/\*\//g, '*​/');
}
